### ISSUE TITLE
Wabt 0.9.2 yanked

### ISSUE THREAD

**Issue by bitdivine** [pepyakin/wabt-rs#76]
Hello Sergei,

Just out of curiosity, why was wabt 0.9.2 yanked from crates.io?  I'm wondering whether I need to update to 10, with the possible breaking changes that might entail.  If it's just a question of deprecation, I can chill out, if there is some deep security flaw or nasty bug I might have to sit up and do something.  0.9.1 hasn't been yanked.  Is rolling back a safe option?

Best wishes, Max

**Comment by pepyakin** [comment]
I am not aware of any security issues with it, however, there were breaking changes in semantic of parsing so that some older versions of wast wasn't working. 

AFAIR, there was a problem with some other project that broke the build and or tests and the easiest way was to just yank wabt. Sorry for inconvenience.

**Comment by bitdivine** [comment]
Thank you for letting me know and thank you for maintaining this! 😊
